---

- name: Download ZAP
  unarchive: >
    src={{ zap_url }}
    dest=/opt
    copy=no

- name: Link zap version
  file: >
    src=/opt/ZAP_{{ zap_version }}
    dest=/opt/zap
    state=link
    owner=root
    group=root

- name: Install init script
  copy: >
    src=zap-init.sh
    dest=/etc/init.d/zap
    mode=0755
    owner=root
    group=root

- name: Install Java
  yum: >
    name=java-1.7.0-openjdk
    state=present
    update_cache=yes

- name: Register and start zap service
  service: >
    name=zap
    state=started
    enabled=yes
