---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 3
  hosts: all
  roles_path: roles

  require_ansible_repo: false
  require_ansible_omnibus: true
  ansible_version: 2.0.0

  require_chef_for_busser: false
  require_ruby_for_busser: true

platforms:
  - name: centos-7.2
    driver_plugin: vagrant
    driver_config:
      box: bento/centos-7.2
    verifier:
      name: busser
      plugin:
        - Ansiblespec
      ruby_bindir: '/usr/bin'

suites:
  - name: default
